spring.application.name=PerfilIA
spring.mongodb.uri=mongodb://localhost:27017/cv-agent
server.port=8080
spring.servlet.encoding.enabled=true
spring.servlet.encoding.charset=UTF-8
spring.servlet.encoding.force=true
openai.api.key=${OPENAI_API_KEY}
openai.api.url=https://api.openai.com/v1/chat/completions